name: lbwbdtts
description: Text to Speak.
version: 0.0.1
homepage: https://github.com/sssolinjie/Lbwbdtts
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.example.lbwbdtts
        pluginClass: LbwbdttsPlugin
      ios:
        pluginClass: LbwbdttsPlugin
